language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc

script:
  - cmake .
  - make

before_deploy:
- if [ "$TRAVIS_OS_NAME" == "linux" ];   then source ./travis/linux.package.sh;   fi

deploy:
  provider: releases
  api_key:
    secure: "SDmI1rknU+c09NwlikEPl0uwpkI+zXHoj38n3pIAKlBxchoycBwoBJpwtRuSQrIT59Sb220xHhjz6WbtHXbko+WlF8Znvd1G9zpIGSopk/gPdbFlGDxbhhBwNqp1YlTGgsHyo2ORaU0KeTyrOBTvZfuzE9tEzK6FrSmL6tXR708="
  file_glob: true
  file: tsc.zip
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"